CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra
BLATT03_1_3A = $(CC) $(CFLAGS) -o blatt03_1_3a.exe blatt03_1_3a.c
BLATT03_1_3B = $(CC) $(CFLAGS) -o blatt03_1_3b.exe blatt03_1_3b.c
BLATT03_1_3C = $(CC) $(CFLAGS) -o blatt03_1_3c.exe blatt03_1_3c.c

all:
	$(BLATT03_1_3A)
	$(BLATT03_1_3B)
	$(BLATT03_1_3C)
	blatt03_1_3a.exe
	blatt03_1_3b.exe
	blatt03_1_3c.exe
blatt03_1_3a:
	$(BLATT03_1_3A)
	blatt03_1_3a.exe
blatt03_1_3b:
	$(BLATT03_1_3B)
	blatt03_1_3b.exe
blatt03_1_3c:
	$(BLATT03_1_3C)
	blatt03_1_3c.exe