CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra
BLATT03_1_1 = $(CC) $(CFLAGS) -o blatt03_1_1.exe blatt03_1_1.c
BLATT03_1_2 = $(CC) $(CFLAGS) -o blatt03_1_2.exe blatt03_1_2.c
BLATT03_1_3A = $(CC) $(CFLAGS) -o blatt03_1_3a.exe blatt03_1_3a.c
BLATT03_1_3B = $(CC) $(CFLAGS) -o blatt03_1_3b.exe blatt03_1_3b.c
BLATT03_1_3C = $(CC) $(CFLAGS) -o blatt03_1_3c.exe blatt03_1_3c.c
BLATT03_2_1 = $(CC) $(CFLAGS) -o blatt03_2_1.exe blatt03_2_1.c
BLATT03_2_2 = $(CC) $(CFLAGS) -o blatt03_2_2.exe blatt03_2_2.c
BLATT03_2_3 = $(CC) $(CFLAGS) -o blatt03_2_3.exe blatt03_2_3.c
BLATT03_2_4 = $(CC) $(CFLAGS) -o blatt03_2_4.exe blatt03_2_4.c
BLATT03_2_5 = $(CC) $(CFLAGS) -o blatt03_2_5.exe blatt03_2_5.c
BLATT03_2_6 = $(CC) $(CFLAGS) -o blatt03_2_6.exe blatt03_2_6.c
BLATT03_2_7 = $(CC) $(CFLAGS) -o blatt03_2_7.exe blatt03_2_7.c

all:
	$(BLATT03_1_1)
	$(BLATT03_1_2)
	$(BLATT03_1_3A)
	$(BLATT03_1_3B)
	$(BLATT03_1_3C)
	$(BLATT03_2_1)
	$(BLATT03_2_2)
	$(BLATT03_2_3)
	$(BLATT03_2_4)
	$(BLATT03_2_5)
	$(BLATT03_2_6)
	blatt03_1_1.exe
	blatt03_1_2.exe
	blatt03_1_3a.exe
	blatt03_1_3b.exe
	blatt03_1_3c.exe
	blatt03_2_1.exe
	blatt03_2_2.exe
	blatt03_2_3.exe
	blatt03_2_4.exe
	blatt03_2_5.exe
	blatt03_2_6.exe
blatt03_1_1:
	$(BLATT03_1_1)
	blatt03_1_1.exe
blatt03_1_2:
	$(BLATT03_1_2)
	blatt03_1_2.exe
blatt03_1_3a:
	$(BLATT03_1_3A)
	blatt03_1_3a.exe
blatt03_1_3b:
	$(BLATT03_1_3B)
	blatt03_1_3b.exe
blatt03_1_3c:
	$(BLATT03_1_3C)
	blatt03_1_3c.exe
blatt03_2_1:
	$(BLATT03_2_1)
	blatt03_2_1.exe