CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra
BLATT06_1 = $(CC) $(CFLAGS) -o blatt06_1.exe blatt06_1.c
BLATT06_2_1 = $(CC) $(CFLAGS) -o blatt06_2_1.exe blatt06_2_1.c

all:
	$(BLATT06_1)
	$(BLATT06_2_1)
	blatt06_1.exe
	blatt06_2_1.exe
blatt06_1:
	$(BLATT06_1)
	blatt06_1.exe
blatt06_2_1:
	$(BLATT06_2_1)
	blatt06_2_1.exe