CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra
BLATT04_1_1A = $(CC) $(CFLAGS) -o blatt04_1_1a.exe blatt04_1_1a.c
BLATT04_1_1B = $(CC) $(CFLAGS) -o blatt04_1_1b.exe blatt04_1_1b.c
BLATT04_1_1C = $(CC) $(CFLAGS) -o blatt04_1_1c.exe blatt04_1_1c.c

all:
	$(BLATT04_1_1A)
	$(BLATT04_1_1B)
	blatt04_1_1a.exe
	blatt04_1_1b.exe
blatt04_1_1a:
	$(BLATT04_1_1A)
	blatt04_1_1a.exe
blatt04_1_1b:
	$(BLATT04_1_1B)
	blatt04_1_1b.exe
blatt04_1_1c:
	$(BLATT04_1_1C)
	blatt04_1_1c.exe